version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Congratulations" present in index.html file"
    post_build:
        commands:
            - echo "Post build phase"

artifacts:
    files:
      - '**/*'
    base-directory: base_dir
    name: build-artifact-name
    discard-paths: no